---
- name: Install and Configure Jenkins CI Server
  hosts: jenkins
  become: yes
  vars:
    java_package: openjdk-17-jdk
    jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
    jenkins_admin_user: admin
    jenkins_admin_password: Admin@123

  tasks:
    # 1️⃣ Ensure base packages are available
    - name: Ensure dependencies are installed
      apt:
        name:
          - gnupg
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    # 2️⃣ Install Java (required for Jenkins)
    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present

    # 3️⃣ Add Jenkins GPG key
    - name: Add Jenkins repo key
      apt_key:
        url: "{{ jenkins_repo_key_url }}"
        state: present

    # 4️⃣ Add Jenkins repository
    - name: Add Jenkins repository
      apt_repository:
        repo: "{{ jenkins_repo_url }}"
        state: present

    # 5️⃣ Install Jenkins
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    # 6️⃣ Ensure Jenkins service is running
    - name: Ensure Jenkins is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

    # 7️⃣ Wait for Jenkins to be ready (port 8080)
    - name: Wait for Jenkins web interface to become available
      uri:
        url: http://localhost:8080/login
        status_code: 200
        validate_certs: no
      register: jenkins_status
      retries: 30
      delay: 10
      until: jenkins_status.status == 200

  handlers:
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
