---
- name: Setup MySQL Database Server
  hosts: dbservers
  become: yes
  vars:
    mysql_root_password: StrongPass123!
    app_db_name: myappdb
    app_db_user: myappuser
    app_db_password: MyApp@123
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache and install dependencies
      apt:
        name:
          - python3-pip
          - python3-dev
          - libmysqlclient-dev
        state: present
        update_cache: yes

    - name: Install Python MySQL library
      pip:
        name: mysqlclient
        executable: pip3

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Ensure MySQL service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password (first-time setup)
      mysql_user:
        login_user: root
        login_password: ""
        user: root
        password: "{{ mysql_root_password }}"
        host_all: yes
      ignore_errors: yes   # Skip if password already set

    - name: Remove anonymous users
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: ""
        host_all: yes
        state: absent

    - name: Remove test database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: test
        state: absent

    - name: Create application database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ app_db_name }}"
        state: present
        encoding: utf8mb4
        collation: utf8mb4_general_ci

    - name: Create application DB user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ app_db_user }}"
        password: "{{ app_db_password }}"
        host: "%"
        priv: "{{ app_db_name }}.*:ALL"
        state: present
