---
- name: Install and Configure ELK Stack (Elasticsearch, Logstash, Kibana)
  hosts: elkservers
  become: yes

  vars:
    es_heap_size: "1g"
    es_port: 9200
    kibana_port: 5601
    logstash_port: 5044

  tasks:
    # -----------------------------
    # Common Setup
    # -----------------------------
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - openjdk-17-jdk
          - wget
          - curl
        state: present
        update_cache: yes

    - name: Add Elastic GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic APT repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    # -----------------------------
    # Elasticsearch
    # -----------------------------
    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: yes

    - name: Configure Elasticsearch JVM heap
      copy:
        dest: /etc/elasticsearch/jvm.options.d/heap.options
        content: |
          -Xms{{ es_heap_size }}
          -Xmx{{ es_heap_size }}
      notify: Restart Elasticsearch

    - name: Configure Elasticsearch port
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "http.port: {{ es_port }}"
      notify: Restart Elasticsearch

    - name: Enable and start Elasticsearch
      service:
        name: elasticsearch
        state: started
        enabled: yes

    # -----------------------------
    # Logstash
    # -----------------------------
    - name: Install Logstash
      apt:
        name: logstash
        state: present

    - name: Configure Logstash input
      copy:
        dest: /etc/logstash/conf.d/input.conf
        content: |
          input {
            beats {
              port => {{ logstash_port }}
            }
          }
      notify: Restart Logstash

    - name: Configure Logstash output
      copy:
        dest: /etc/logstash/conf.d/output.conf
        content: |
          output {
            elasticsearch {
              hosts => ["http://localhost:{{ es_port }}"]
              index => "logs-%{+YYYY.MM.dd}"
            }
          }
      notify: Restart Logstash

    - name: Enable and start Logstash
      service:
        name: logstash
        state: started
        enabled: yes

    # -----------------------------
    # Kibana
    # -----------------------------
    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Configure Kibana port
      lineinfile:
        path: /etc/kibana/kibana.yml
        line: "server.port: {{ kibana_port }}"
      notify: Restart Kibana

    - name: Enable and start Kibana
      service:
        name: kibana
        state: started
        enabled: yes

  handlers:
    - name: Restart Elasticsearch
      service:
        name: elasticsearch
        state: restarted

    - name: Restart Logstash
      service:
        name: logstash
        state: restarted

    - name: Restart Kibana
      service:
        name: kibana
        state: restarted
