---
- name: Install and Configure Apache Tomcat
  hosts: appservers
  become: yes
  vars:
    java_package: openjdk-17-jdk
    tomcat_version: "10.1.49"
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.49/bin/apache-tomcat-10.1.49.tar.gz"
    tomcat_install_dir: /opt/tomcat
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_service_name: tomcat

  tasks:
    - name: Install Java (required for Tomcat)
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        create_home: no
        shell: /bin/false

    - name: Download Tomcat tar.gz
      get_url:
        url: "{{ tomcat_url }}"
        dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz

    - name: Create Tomcat installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Extract Tomcat archive
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Set permissions on Tomcat directories
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/{{ tomcat_service_name }}.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_group }}

          Environment="JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
          Environment="CATALINA_PID={{ tomcat_install_dir }}/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ tomcat_install_dir }}"
          Environment="CATALINA_BASE={{ tomcat_install_dir }}"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"

          ExecStart={{ tomcat_install_dir }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh

          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Tomcat
      service:
        name: "{{ tomcat_service_name }}"
        state: started
        enabled: yes

    - name: Deploy sample index.html
      copy:
        dest: "{{ tomcat_install_dir }}/webapps/ROOT/index.html"
        content: |
          <html>
          <head><title>Welcome to Tomcat</title></head>
          <body>
            <h1>Tomcat Installed via Ansible 🚀</h1>
          </body>
          </html>
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0644'
